# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue! ğŸ™
   
  If you're reporting a bug ğŸ, please make sure you include steps to reproduce
  it. If you're requesting a feature ğŸ, please provide real use cases that
  would benefit the community ğŸ‘ª.
   
  To help make this a smooth process, please be sure you have first read our
  [guidelines for contributing](https://github.com/hyperweavers/release-automation-sample-2/blob/master/CONTRIBUTING.md) ğŸ“–.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ’– Thanks for opening this pull request! ğŸ’–
   
  To help make this a smooth process, please be sure you have first read our
  [guidelines for contributing](https://github.com/hyperweavers/release-automation-sample-2/blob/master/CONTRIBUTING.md) ğŸ“–.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸ‰ğŸ‰ğŸ‰ Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
   
  You're helping make Electron App awesome! ğŸ™Œ

# It is recommend to include as many gifs and emojis as possible
